export {
  APP_CATALOG,
  aiApps,
  appOpensInNewTab,
  availableApps,
  availableSwitcherApps,
  discoverApps,
  externalApps,
  externalSaasApps,
  firstPartyExternalSaasApps,
  futureApps,
  getAppById,
  launchableApps,
  linkedExternalSaasApps,
  partnerExternalSaasApps,
  yourApps,
} from '@registry/appCatalog';
