import {
  AlertCircle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowUp,
  Baseline,
  Bold,
  Box,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ClipboardCheck,
  Clock,
  Columns3,
  Copy,
  Download,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileImage,
  FileSpreadsheet,
  FileText,
  FileType,
  Filter,
  Folder,
  FolderOpen,
  FolderTree,
  GripVertical,
  History,
  Image,
  Inbox,
  Indent,
  Italic,
  Link,
  Link2Off,
  List,
  ListOrdered,
  Loader2,
  Mail,
  Maximize2,
  Minimize,
  Minimize2,
  MoreHorizontal,
  Outdent,
  PackagePlus,
  PackageX,
  Palette,
  Pencil,
  Plus,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  Save,
  Search,
  SearchX,
  Send,
  SquarePen,
  Strikethrough,
  Tag,
  Table2,
  ToggleLeft,
  ToggleRight,
  Trash2,
  Truck,
  Underline,
  Undo2,
  Redo2,
  Upload,
  User,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

/**
 * CFR_Admin uses `lucide-react` as its icon library (project convention), unlike the
 * reference project this component library was ported from (Font Awesome class names).
 * This map preserves the reference project's `AppIconName` keys — used throughout the
 * ported dataTable/formControls code — but resolves each to a `lucide-react` component
 * instead of an FA class string. Only names actually referenced by the ported code are
 * included; add more here if a newly-ported file needs another icon.
 */
export const APP_ICONS = {
  alertCircle: AlertCircle,
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  addBox: Box,
  baseline: Baseline,
  bold: Bold,
  calendar: Calendar,
  calendarClock: CalendarClock,
  check: Check,
  checkCircle2: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUp: ChevronsUp,
  clear: X,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  close: X,
  columns3: Columns3,
  copy: Copy,
  download: Download,
  expand: Expand,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  fileIcon: File,
  fileImage: FileImage,
  filePdf: FileType,
  fileSpreadsheet: FileSpreadsheet,
  fileText: FileText,
  fileWord: FileText,
  filter: Filter,
  folder: Folder,
  folderOpen: FolderOpen,
  folderTree: FolderTree,
  history: History,
  imageIcon: Image,
  imagePlus: Image,
  inbox: Inbox,
  indent: Indent,
  italic: Italic,
  link: Link,
  link2Off: Link2Off,
  list: List,
  listOrdered: ListOrdered,
  loader2: Loader2,
  mail: Mail,
  maximize2: Maximize2,
  minimize: Minimize,
  minimize2: Minimize2,
  moreHorizontal: MoreHorizontal,
  outdent: Outdent,
  packagePlus: PackagePlus,
  packageX: PackageX,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  printer: Printer,
  qrCode: QrCode,
  receipt: Receipt,
  redo2: Redo2,
  refreshCw: RefreshCw,
  rowDragHandle: GripVertical,
  rowRemove: X,
  save: Save,
  search: Search,
  searchX: SearchX,
  send: Send,
  sort: ArrowUp,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  squarePen: SquarePen,
  strikethrough: Strikethrough,
  table2: Table2,
  tag: Tag,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  trash2: Trash2,
  truckFast: Truck,
  underline: Underline,
  undo2: Undo2,
  upload: Upload,
  user: User,
  x: X,
  xCircle: XCircle,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;

export function isAppIconName(value: string): value is AppIconName {
  return value in APP_ICONS;
}
