import { type ChangeEvent, useMemo, useState } from 'react';
import { DashboardHeader } from '@shared/app/components/DashboardHeader';
import { FilterField } from '../components/FilterField';
import { lessonCourses, reportStudents } from '../lessonPlanData';

const stages=['All','Level 1','Level 2','Level 3','Mastery'];
const concepts=['Photosynthesis','Plant respiration','Energy transfer'];
export function ReportsPage(){
  const [stage,setStage]=useState('All'); const [course,setCourse]=useState('Science 7'); const [concept,setConcept]=useState('Photosynthesis'); const [term,setTerm]=useState('Trimester 1'); const [query,setQuery]=useState('');
  const rows=useMemo(()=>reportStudents.filter((item)=>(stage==='All'||item.stage===stage)&&(!query.trim()||item.name.toLowerCase().includes(query.toLowerCase()))),[stage,query]);
  const counts=stages.slice(1).map((item)=>[item,reportStudents.filter((student)=>student.stage===item).length] as const);
  return <main className="dashboard-content dashboard-stack lesson-screen"><DashboardHeader eyebrow="Learning evidence" title="Reports" status={<span className="lesson-count-badge">{course} · {concept}</span>}/><section className="lesson-panel"><div className="lesson-report-filters"><FilterField label="Class / course" value={course} onChange={setCourse} options={lessonCourses}/><FilterField label="Concept" value={concept} onChange={setConcept} options={concepts}/><FilterField label="Term" value={term} onChange={setTerm} options={['Trimester 1','Trimester 2','Trimester 3']}/><label className="lesson-field lesson-field--search"><span>Search student</span><input value={query} onChange={(event:ChangeEvent<HTMLInputElement>)=>setQuery(event.target.value)} placeholder="Student name"/></label></div><div className="lesson-report-kpis"><article><strong>24</strong><span>Student count</span></article><article><strong>{reportStudents.length}</strong><span>Attended</span></article><article><strong>19</strong><span>Yet to start</span></article>{counts.map(([item,count])=><article key={item}><strong>{count}</strong><span>{item==='Mastery'?'Mastery':`At ${item}`}</span></article>)}</div><header className="lesson-panel-heading"><div><span>XtraCoach learning</span><h2>Concept progress</h2><p>Student counts and learning evidence only — no percentages, rankings, or grades.</p></div><div className="lesson-tabs lesson-tabs--compact">{stages.map((item)=><button type="button" key={item} className={stage===item?'is-active':''} onClick={()=>setStage(item)}>{item}</button>)}</div></header><div className="lesson-stage-distribution">{counts.map(([item,count])=><div key={item}><span>{item}</span><div><i style={{width:`${Math.max(8,count/reportStudents.length*100)}%`}}/></div><strong>{count}</strong></div>)}</div><div className="lesson-table-scroll"><table className="lesson-enterprise-table"><thead><tr><th>Student</th><th>Current stage</th><th>Concepts mastered</th><th>Effort</th><th>Last accessed</th></tr></thead><tbody>{rows.map((student)=><tr key={student.id}><td><strong>{student.name}</strong><span>{student.id}</span></td><td><span className={`lesson-stage-chip lesson-stage-chip--${student.stage.toLowerCase().replace(' ','-')}`}>{student.stage}</span></td><td>{student.concepts} of 3</td><td>{student.effort}</td><td>{student.lastAccessed}</td></tr>)}</tbody></table></div></section></main>
}
