[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/integrations/app-switcher/app-switcher.js"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    Access-Control-Allow-Origin = "*"

