-- Copyright (c) OptionC. All rights reserved.
-- App Hub and the sign-in showcase read the same Products/GetProducts list
-- as CFR Admin (Acutis_Products_CRUD ActionId 4 / ProductOutput).
-- Do not replace that stored procedure with a hub-only procedure.
