-- Copyright (c) OptionC. All rights reserved.
-- "Suggest a product" public request/approval workflow - STORED PROCEDURE ONLY.
-- Requires 021_Acutis_ProductRequest_Tables.sql and 024_Acutis_Product_SecurityKey.sql to have
-- already been run.
--
-- Stored procedure [dbo].[Acutis_ProductRequest] ActionId map:
--   ActionId 1: Insert a new product request (public submit, no @InsertedBy - anonymous)
--   ActionId 2: GET All product requests (admin review list), optional @RequestStatus filter
--   ActionId 3: GET by Id (header + features), for the admin review/detail view
--   ActionId 4: Approve - transaction: insert into [core].[Product] + [core].[ProductFeature],
--               mark the request approved, link it to the new ProductId. @SecurityKey is
--               generated by the caller (ProductRequestService.ApproveProductRequestAsync,
--               CFR.AcutisService) and saved onto the new core.Product row as-is - this
--               procedure does not generate it itself.
--   ActionId 5: Reject - mark the request rejected with a reason, no catalog changes
--   ActionId 6: GET notification recipients - who to email when a request comes in. Resolves the
--               configured recipient from [request].[ProductRequestSettings] (set via ActionId 7
--               from the CFR Settings page) when it's an active user; otherwise falls back to
--               every active 'Platform Admin' role user (same fallback 008_AccessRequest.sql's
--               ActionId 5 uses for products with no contact set). Deliberately reads the setting
--               from this shared table rather than trusting an @NotifyUserId passed in by the
--               caller - CFR.Acutis and CFR.Portal are separate processes with their own, separate
--               _configurationSettings.json files, so a value read from one service's local file
--               (as this used to do) is invisible to the other and was always stale/null there.
--   ActionId 7: SAVE the configured notification recipient (CFR Settings page), upserting
--               [request].[ProductRequestSettings].
--   ActionId 8: GET the currently configured notification recipient, for the CFR Settings /
--               Email Settings page to display.
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF OBJECT_ID(N'[dbo].[Acutis_ProductRequest]', N'P') IS NOT NULL
    DROP PROCEDURE [dbo].[Acutis_ProductRequest];
GO

CREATE PROCEDURE [dbo].[Acutis_ProductRequest]
    @ActionId INT,
    -- Product request parameters
    @ProductRequestId INT = 0,
    @ProductName NVARCHAR(200) = NULL,
    @ShortName NVARCHAR(100) = NULL,
    @SubCategoryName NVARCHAR(200) = NULL,
    @ProdDescription NVARCHAR(MAX) = NULL,
    @ExternalPageUrl NVARCHAR(500) = NULL,
    @NavigationTarget NVARCHAR(50) = NULL,
    @Features NVARCHAR(MAX) = NULL, -- pipe-delimited, same wire format as Acutis_Products
    @LogoName NVARCHAR(500) = NULL, -- file name, already saved into Acutis/Attachment/Products
    @RequesterName NVARCHAR(200) = NULL,
    @RequesterEmail NVARCHAR(256) = NULL,
    @OrganizationName NVARCHAR(200) = NULL,
    @SecurityKey NVARCHAR(100) = NULL, -- ActionId 4 only: generated by the caller, saved onto the new core.Product row
    @RequestStatus INT = NULL,
    @DecisionRemarks NVARCHAR(1000) = NULL,
    @NotifyUserId BIGINT = NULL, -- ActionId 6 only: Email Settings' configured notification recipient
    -- Audit & output parameters
    @InsertedBy BIGINT = NULL,
    @UpdatedBy BIGINT = NULL,
    @ReturnValue INT = NULL OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @ReturnValue = 0;
    SET @InsertedBy = NULLIF(@InsertedBy, 0);
    SET @UpdatedBy = NULLIF(@UpdatedBy, 0);
    SET @ProductName = NULLIF(LTRIM(RTRIM(@ProductName)), N'');
    SET @ShortName = NULLIF(LTRIM(RTRIM(@ShortName)), N'');
    SET @SubCategoryName = NULLIF(LTRIM(RTRIM(@SubCategoryName)), N'');
    SET @ProdDescription = NULLIF(LTRIM(RTRIM(@ProdDescription)), N'');
    SET @ExternalPageUrl = NULLIF(LTRIM(RTRIM(@ExternalPageUrl)), N'');
    SET @LogoName = NULLIF(LTRIM(RTRIM(@LogoName)), N'');
    SET @NavigationTarget = NULLIF(LTRIM(RTRIM(@NavigationTarget)), N'');
    SET @RequesterName = NULLIF(LTRIM(RTRIM(@RequesterName)), N'');
    SET @RequesterEmail = NULLIF(LTRIM(RTRIM(@RequesterEmail)), N'');
    SET @OrganizationName = NULLIF(LTRIM(RTRIM(@OrganizationName)), N'');
    SET @DecisionRemarks = NULLIF(LTRIM(RTRIM(@DecisionRemarks)), N'');

    ---------------------------------------------------------------------------
    -- ActionId 1: Insert a new product request (public submit)
    ---------------------------------------------------------------------------
    IF @ActionId = 1
    BEGIN
        IF @ProductName IS NULL OR @ProdDescription IS NULL OR @RequesterName IS NULL OR @RequesterEmail IS NULL
        BEGIN
            SET @ReturnValue = -95;
            RETURN @ReturnValue;
        END

        DECLARE @NewRequestId INT;

        BEGIN TRY
            BEGIN TRANSACTION;

            INSERT INTO [request].[ProductRequest]
            (
                [ProductName], [ShortName], [SubCategoryName], [ProdDescription], [ExternalPageUrl],
                [NavigationTarget], [LogoName], [RequesterName], [RequesterEmail], [OrganizationName],
                [RequestStatus], [InsertedDate], [InsertedBy], [IsDeleted]
            )
            VALUES
            (
                @ProductName, @ShortName, @SubCategoryName, @ProdDescription, @ExternalPageUrl,
                @NavigationTarget, @LogoName, @RequesterName, @RequesterEmail, @OrganizationName,
                1, SYSUTCDATETIME(), @InsertedBy, 0
            );

            SET @NewRequestId = SCOPE_IDENTITY();

            IF @Features IS NOT NULL
            BEGIN
                INSERT INTO [request].[ProductRequestFeature]
                (
                    [ProductRequestId], [FeatureName], [InsertedDate], [IsDeleted]
                )
                SELECT
                    @NewRequestId,
                    LTRIM(RTRIM(value)),
                    SYSUTCDATETIME(),
                    0
                FROM STRING_SPLIT(@Features, '|')
                WHERE LTRIM(RTRIM(value)) <> N'';
            END

            INSERT INTO [request].[ProductRequestStatusHistory]
            (
                [ProductRequestId], [StatusValue], [Remarks], [ChangedBy], [InsertedDate]
            )
            VALUES
            (
                @NewRequestId, 1, N'Request submitted', NULL, SYSUTCDATETIME()
            );

            COMMIT TRANSACTION;
            SET @ReturnValue = @NewRequestId;
            RETURN @ReturnValue;
        END TRY
        BEGIN CATCH
            IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
            THROW;
        END CATCH
    END

    ---------------------------------------------------------------------------
    -- ActionId 2: GET All product requests (admin review list)
    ---------------------------------------------------------------------------
    IF @ActionId = 2
    BEGIN
        SELECT
            r.[ProductRequestId],
            r.[ProductName],
            r.[ShortName],
            r.[SubCategoryName],
            r.[ProdDescription],
            r.[ExternalPageUrl],
            r.[NavigationTarget],
            r.[LogoName],
            r.[RequesterName],
            r.[RequesterEmail],
            r.[OrganizationName],
            r.[RequestStatus],
            r.[ReviewedBy],
            r.[ReviewedDate],
            r.[DecisionRemarks],
            r.[ApprovedProductId],
            r.[InsertedDate]
        FROM [request].[ProductRequest] AS r
        WHERE r.[IsDeleted] = 0
          AND (@RequestStatus IS NULL OR r.[RequestStatus] = @RequestStatus)
        ORDER BY r.[InsertedDate] DESC;

        RETURN 0;
    END

    ---------------------------------------------------------------------------
    -- ActionId 3: GET by Id (header + features)
    ---------------------------------------------------------------------------
    IF @ActionId = 3
    BEGIN
        SELECT
            r.[ProductRequestId],
            r.[ProductName],
            r.[ShortName],
            r.[SubCategoryName],
            r.[ProdDescription],
            r.[ExternalPageUrl],
            r.[NavigationTarget],
            r.[LogoName],
            r.[RequesterName],
            r.[RequesterEmail],
            r.[OrganizationName],
            r.[RequestStatus],
            r.[ReviewedBy],
            r.[ReviewedDate],
            r.[DecisionRemarks],
            r.[ApprovedProductId],
            r.[InsertedDate]
        FROM [request].[ProductRequest] AS r
        WHERE r.[ProductRequestId] = @ProductRequestId
          AND r.[IsDeleted] = 0;

        SELECT
            f.[FeatureName]
        FROM [request].[ProductRequestFeature] AS f
        WHERE f.[ProductRequestId] = @ProductRequestId
          AND f.[IsDeleted] = 0
        ORDER BY f.[ProductRequestFeatureId];

        RETURN 0;
    END

    ---------------------------------------------------------------------------
    -- ActionId 4: Approve - copy the request into [core].[Product] / [core].[ProductFeature]
    ---------------------------------------------------------------------------
    IF @ActionId = 4
    BEGIN
        DECLARE @ExistingStatus INT;
        DECLARE @ApproveProductName NVARCHAR(200);
        DECLARE @ApproveShortName NVARCHAR(100);
        DECLARE @ApproveSubCategoryName NVARCHAR(200);
        DECLARE @ApproveProdDescription NVARCHAR(MAX);
        DECLARE @ApproveExternalPageUrl NVARCHAR(500);
        DECLARE @ApproveNavigationTarget NVARCHAR(50);
        DECLARE @ApproveLogoName NVARCHAR(500);
        DECLARE @NewProductId INT;

        SELECT
            @ExistingStatus = r.[RequestStatus],
            @ApproveProductName = r.[ProductName],
            @ApproveShortName = r.[ShortName],
            @ApproveSubCategoryName = r.[SubCategoryName],
            @ApproveProdDescription = r.[ProdDescription],
            @ApproveExternalPageUrl = r.[ExternalPageUrl],
            @ApproveNavigationTarget = r.[NavigationTarget],
            @ApproveLogoName = r.[LogoName]
        FROM [request].[ProductRequest] AS r
        WHERE r.[ProductRequestId] = @ProductRequestId
          AND r.[IsDeleted] = 0;

        IF @ExistingStatus IS NULL OR @ExistingStatus <> 1
        BEGIN
            SET @ReturnValue = -95; -- not found, or already reviewed
            RETURN @ReturnValue;
        END

        IF EXISTS (
            SELECT 1 FROM [core].[Product]
            WHERE LOWER(LTRIM(RTRIM([ProductName]))) = LOWER(@ApproveProductName)
              AND [IsDeleted] = 0
        )
        BEGIN
            SET @ReturnValue = -99; -- a product with this name already exists
            RETURN @ReturnValue;
        END

        BEGIN TRY
            BEGIN TRANSACTION;

            -- [core].[Product].[ProductId] is NOT an identity column on the live database (this
            -- table predates this repo and has never had an insert path before now - UpdateProduct
            -- is the only prior write). UPDLOCK/HOLDLOCK serializes concurrent approvals so two
            -- requests approved at the same instant can't compute the same next id.
            SELECT @NewProductId = ISNULL(MAX([ProductId]), 0) + 1
            FROM [core].[Product] WITH (UPDLOCK, HOLDLOCK);

            INSERT INTO [core].[Product]
            (
                [ProductId], [ProductName], [ShortName], [SubCategoryName], [ProdDescription], [ExternalPageUrl],
                [LogoName], [IsActive], [ProductStatus], [NavigationTarget], [SecurityKey], [CreatedDate], [InsertedBy], [IsDeleted]
            )
            VALUES
            (
                @NewProductId, @ApproveProductName, @ApproveShortName, @ApproveSubCategoryName, @ApproveProdDescription,
                @ApproveExternalPageUrl, @ApproveLogoName, 1, 1, @ApproveNavigationTarget, @SecurityKey, SYSUTCDATETIME(), @UpdatedBy, 0
            );

            INSERT INTO [core].[ProductFeature]
            (
                [ProductId], [FeatureName], [IsActive], [CreatedDate], [InsertedBy], [IsDeleted]
            )
            SELECT
                @NewProductId,
                f.[FeatureName],
                1,
                SYSUTCDATETIME(),
                @UpdatedBy,
                0
            FROM [request].[ProductRequestFeature] AS f
            WHERE f.[ProductRequestId] = @ProductRequestId
              AND f.[IsDeleted] = 0;

            UPDATE [request].[ProductRequest]
            SET
                [RequestStatus] = 2,
                [ReviewedBy] = @UpdatedBy,
                [ReviewedDate] = SYSUTCDATETIME(),
                [DecisionRemarks] = @DecisionRemarks,
                [ApprovedProductId] = @NewProductId,
                [UpdatedDate] = SYSUTCDATETIME(),
                [UpdatedBy] = @UpdatedBy
            WHERE [ProductRequestId] = @ProductRequestId;

            INSERT INTO [request].[ProductRequestStatusHistory]
            (
                [ProductRequestId], [StatusValue], [Remarks], [ChangedBy], [InsertedDate]
            )
            VALUES
            (
                @ProductRequestId, 2, @DecisionRemarks, @UpdatedBy, SYSUTCDATETIME()
            );

            COMMIT TRANSACTION;
            SET @ReturnValue = @NewProductId;
            RETURN @ReturnValue;
        END TRY
        BEGIN CATCH
            IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
            THROW;
        END CATCH
    END

    ---------------------------------------------------------------------------
    -- ActionId 5: Reject - no catalog changes, just records the decision
    ---------------------------------------------------------------------------
    IF @ActionId = 5
    BEGIN
        IF @ProductRequestId <= 0 OR NOT EXISTS (
            SELECT 1 FROM [request].[ProductRequest]
            WHERE [ProductRequestId] = @ProductRequestId
              AND [RequestStatus] = 1
              AND [IsDeleted] = 0
        )
        BEGIN
            SET @ReturnValue = -95; -- not found, or already reviewed
            RETURN @ReturnValue;
        END

        UPDATE [request].[ProductRequest]
        SET
            [RequestStatus] = 3,
            [ReviewedBy] = @UpdatedBy,
            [ReviewedDate] = SYSUTCDATETIME(),
            [DecisionRemarks] = @DecisionRemarks,
            [UpdatedDate] = SYSUTCDATETIME(),
            [UpdatedBy] = @UpdatedBy
        WHERE [ProductRequestId] = @ProductRequestId;

        INSERT INTO [request].[ProductRequestStatusHistory]
        (
            [ProductRequestId], [StatusValue], [Remarks], [ChangedBy], [InsertedDate]
        )
        VALUES
        (
            @ProductRequestId, 3, @DecisionRemarks, @UpdatedBy, SYSUTCDATETIME()
        );

        SET @ReturnValue = @ProductRequestId;
        RETURN @ReturnValue;
    END

    ---------------------------------------------------------------------------
    -- ActionId 6: GET notification recipients for a new product request.
    -- Resolves the configured recipient from [request].[ProductRequestSettings] (ignores any
    -- @NotifyUserId passed by the caller - see the header comment above) when it's an active user
    -- with an email; otherwise falls back to every active 'Platform Admin' role user, same as
    -- 008_AccessRequest.sql's ActionId 5 fallback.
    ---------------------------------------------------------------------------
    IF @ActionId = 6
    BEGIN
        DECLARE @ConfiguredNotifyUserId BIGINT;
        SELECT @ConfiguredNotifyUserId = [NotifyUserId]
        FROM [request].[ProductRequestSettings]
        WHERE [Id] = 1;

        IF @ConfiguredNotifyUserId IS NOT NULL AND EXISTS (
            SELECT 1 FROM [auth].[AcutisUser]
            WHERE [UserId] = @ConfiguredNotifyUserId
              AND [IsDeleted] = 0
              AND [IsActive] = 1
              AND [IsLocked] = 0
              AND NULLIF(LTRIM(RTRIM([Email])), N'') IS NOT NULL
        )
        BEGIN
            SELECT DISTINCT LTRIM(RTRIM(u.[Email])) AS [EMail]
            FROM [auth].[AcutisUser] u
            WHERE u.[UserId] = @ConfiguredNotifyUserId
              AND u.[IsDeleted] = 0
              AND u.[IsActive] = 1
              AND u.[IsLocked] = 0;

            RETURN 0;
        END

        SELECT DISTINCT LTRIM(RTRIM(u.[Email])) AS [EMail]
        FROM [auth].[AcutisUser] u
        INNER JOIN [auth].[AcutisRole] r
            ON r.[RoleId] = u.[RoleId]
           AND r.[IsDeleted] = 0
        WHERE u.[IsDeleted] = 0
          AND u.[IsActive] = 1
          AND u.[IsLocked] = 0
          AND r.[RoleName] = N'Platform Admin'
          AND NULLIF(LTRIM(RTRIM(u.[Email])), N'') IS NOT NULL;

        RETURN 0;
    END

    ---------------------------------------------------------------------------
    -- ActionId 7: SAVE the configured notification recipient (CFR Settings page).
    ---------------------------------------------------------------------------
    IF @ActionId = 7
    BEGIN
        UPDATE [request].[ProductRequestSettings]
        SET
            [NotifyUserId] = @NotifyUserId,
            [UpdatedDate] = SYSUTCDATETIME(),
            [UpdatedBy] = @UpdatedBy
        WHERE [Id] = 1;

        SET @ReturnValue = 1;
        RETURN @ReturnValue;
    END

    ---------------------------------------------------------------------------
    -- ActionId 8: GET the currently configured notification recipient.
    ---------------------------------------------------------------------------
    IF @ActionId = 8
    BEGIN
        SELECT [NotifyUserId]
        FROM [request].[ProductRequestSettings]
        WHERE [Id] = 1;

        RETURN 0;
    END
END
GO
