global using CFR.Base;
global using CFR.Common;
global using CFR.DBEngine;
global using CFR.DataSync;
global using CFR.DataSyncInfrastructure.Models.Input;
global using CFR.DataSyncInfrastructure.Models.Output;
global using CFR.DataSyncService.Interfaces.OrganizationSync;
global using CFR.DataSyncService.Interfaces.Security;
global using CFR.DataSyncService.Interfaces.UserSync;
global using CFR.DataSyncService.Models.Security;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using System.Reflection;
global using System.Resources;
global using System.Text;
global using System.Text.Json;
global using static CFR.Common.Constant;
global using static CFR.CommonService.APIActionName;
