import { DashboardHeader } from '@shared/app/components/DashboardHeader';

const steps=[
  {n:'01',title:'Generate',owner:'School → Lesson service',body:'Send school, course, grade, date, and lesson basics to create a planning draft.',code:'POST /v1/lessons/generate'},
  {n:'02',title:'Store',owner:'Lesson service',body:'Store lesson sections, question banks, and learning-path rules against the lesson reference.',code:'201 · lesson_id · draft'},
  {n:'03',title:'Review & approve',owner:'Teacher → Lesson service',body:'Teachers review generated content, edit it, and explicitly approve availability.',code:'POST /v1/lessons/{id}/approve'},
  {n:'04',title:'Serve learning checks',owner:'Student portal → XtraCoach',body:'Approved lessons serve the next learning check using an anonymous student reference.',code:'GET /v1/coach/{lesson}/next'},
  {n:'05',title:'Write evidence home',owner:'XtraCoach → School',body:'Final responses and learning evidence return to the school system of record.',code:'POST /optionc/api/xc-evidence'},
  {n:'06',title:'Improvement report',owner:'Student only',body:'Students see concepts mastered and effort guidance. It is never used as a grade or ranking.',code:'GET /v1/students/{id}/improvement-report'},
];
export function IntegrationPage(){return <main className="dashboard-content dashboard-stack lesson-screen"><DashboardHeader eyebrow="Platform architecture" title="Agent Integration Flow" status={<span className="lesson-count-badge">6-step contract</span>}/><section className="lesson-panel lesson-integration"><header className="lesson-panel-heading"><div><span>Service boundary</span><h2>School system + XtraCoach responsibilities</h2><p>Lesson planning stays reviewable by teachers while student identity and grading remain within the school system.</p></div></header><div className="lesson-integration-flow">{steps.map((step)=><article key={step.n}><span>{step.n}</span><div><small>{step.owner}</small><h3>{step.title}</h3><p>{step.body}</p><code>{step.code}</code></div></article>)}</div><div className="lesson-boundaries"><article><span>Lesson service</span><strong>Lesson sections · question banks · learning paths</strong><p>Keyed by partner, school, and lesson reference. No student PII is required for lesson generation.</p></article><article><span>School system</span><strong>Rosters · identity · final responses · availability</strong><p>The school remains the system of record for student identity and learning evidence.</p></article></div></section></main>}
