global using CFR.Acutis;
global using CFR.AcutisInfrastructure.Models.Input;
global using CFR.AcutisInfrastructure.Models.Output;
global using CFR.AcutisService.Interfaces.AcutisAuthentication;
global using CFR.AcutisService.Interfaces.Administration;
global using CFR.AcutisService.Interfaces.Profile;
global using CFR.Base;
global using CFR.Common;
global using CFR.CommonService;
global using CFR.DBEngine;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using System.Reflection;
global using System.Resources;
global using System.Text;
global using static CFR.Common.Constant;
global using static CFR.CommonService.APIActionName;
