import { type ChangeEvent, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { DashboardHeader } from '@shared/app/components/DashboardHeader';
import { lessons } from '../lessonPlanData';

type Stage='welcome'|'orientation'|'level1'|'reteach1'|'level2'|'reteach2'|'level3'|'mastery';
const order:Stage[]=['orientation','level1','level2','level3','mastery'];
const questions:{[K in 'level1'|'level2'|'level3']:{prompt:string;options?:string[]}}={
  level1:{prompt:'What gas do plants take in during photosynthesis?',options:['Oxygen','Carbon dioxide','Nitrogen','Water vapor']},
  level2:{prompt:'Which statements explain how sunlight supports photosynthesis?',options:['It provides light energy','Leaves capture the energy','It replaces water','It becomes soil']},
  level3:{prompt:'Explain why photosynthesis is essential for the food chain.'},
};

export function CoachPlayerPage(){
  const navigate=useNavigate();const {lessonId}=useParams();const lesson=lessons.find((item)=>item.id===lessonId)??lessons.find((item)=>item.id==='lp-105')!;
  const [stage,setStage]=useState<Stage>('welcome'); const [answer,setAnswer]=useState(''); const [checks,setChecks]=useState<string[]>([]);
  const activeIndex=useMemo(()=>Math.max(0,order.indexOf(stage as Stage)),[stage]);
  const question=stage==='level1'||stage==='level2'||stage==='level3'?questions[stage]:null;
  const next=()=>{if(stage==='welcome')setStage('orientation');else if(stage==='orientation')setStage('level1');else if(stage==='level1')setStage('level2');else if(stage==='level2')setStage('level3');else if(stage==='level3')setStage('mastery');};
  const reTeach=()=>setStage(stage==='level1'?'reteach1':'reteach2');
  return <main className="dashboard-content dashboard-stack lesson-screen lesson-player-page"><DashboardHeader eyebrow="Student learning · XtraCoach" title={lesson.title} actions={<button type="button" className="action-secondary" onClick={()=>navigate('/student-learning')}>Back to My Learning</button>}/><section className="lesson-player"><div className="lesson-player-progress">{['Level 1','Level 2','Level 3','Mastery'].map((label,index)=><div key={label} className={stage==='mastery'||index<activeIndex?'is-complete':index===activeIndex&&stage!=='welcome'&&stage!=='orientation'?'is-active':''}><span>{stage==='mastery'||index<activeIndex?'✓':index+1}</span><b>{label}</b></div>)}</div>{stage==='welcome'?<PlayerWelcome onStart={next}/>:stage==='orientation'?<PlayerOrientation onReady={next}/>:stage==='reteach1'||stage==='reteach2'?<ReTeach level={stage==='reteach1'?1:2} onContinue={()=>setStage(stage==='reteach1'?'level1':'level2')}/>:stage==='mastery'?<Mastery onDone={()=>navigate('/student-learning')}/>:question?<Question stage={stage as 'level1'|'level2'|'level3'} prompt={question.prompt} options={question.options} answer={answer} checks={checks} onAnswer={setAnswer} onChecks={setChecks} onPass={()=>{setAnswer('');setChecks([]);next();}} onSupport={reTeach}/>:null}</section></main>
}
function PlayerWelcome({onStart}:{onStart:()=>void}){return <div className="lesson-player-card lesson-player-card--welcome"><span>AI learning companion</span><h2>Let's learn this concept together.</h2><p>Your learning path adapts when you need another explanation. This practice is for learning and is never a grade.</p><button type="button" className="action-primary" onClick={onStart}>Start learning</button></div>}
function PlayerOrientation({onReady}:{onReady:()=>void}){return <div className="lesson-player-card"><span>Orientation</span><h2>Photosynthesis</h2><p>Photosynthesis is the process plants use to make food by combining light energy, water, and carbon dioxide.</p><button type="button" className="action-primary" onClick={onReady}>I'm ready</button></div>}
function ReTeach({level,onContinue}:{level:number;onContinue:()=>void}){return <div className="lesson-player-card lesson-player-card--support"><span>Re-teach · Level {level}</span><h2>{level===1?"Let's try another way.":"Let's review this concept again."}</h2><p>{level===1?'Plants take in carbon dioxide from the air and use it with water and sunlight to make food.':'Sunlight is the energy source. Chlorophyll in leaves captures light energy and helps convert water and carbon dioxide into food.'}</p><button type="button" className="action-primary" onClick={onContinue}>Try another question</button></div>}
function Mastery({onDone}:{onDone:()=>void}){return <div className="lesson-player-card lesson-player-card--mastery"><span>Concept mastery</span><h2>Photosynthesis mastered</h2><p>You worked through the full learning path. Your improvement report is visible to you and is not a grade.</p><div className="lesson-mastery-list"><span>✓ Gas exchange in photosynthesis</span><span>✓ Role of sunlight</span><span>✓ Photosynthesis in the food chain</span></div><button type="button" className="action-primary" onClick={onDone}>Return to My Learning</button></div>}
function Question({stage,prompt,options,answer,checks,onAnswer,onChecks,onPass,onSupport}:{stage:'level1'|'level2'|'level3';prompt:string;options?:string[];answer:string;checks:string[];onAnswer:(value:string)=>void;onChecks:(values:string[])=>void;onPass:()=>void;onSupport:()=>void}){return <div className="lesson-player-card"><span>{stage.replace('level','Level ')} · Learning check</span><h2>{prompt}</h2>{stage==='level3'?<textarea rows={5} value={answer} onChange={(event: ChangeEvent<HTMLTextAreaElement>)=>onAnswer(event.target.value)} placeholder="Write your response"/>:<div className="lesson-answer-options">{options?.map((option)=>stage==='level2'?<label key={option}><input type="checkbox" checked={checks.includes(option)} onChange={()=>onChecks(checks.includes(option)?checks.filter((item)=>item!==option):[...checks,option])}/><span>{option}</span></label>:<label key={option}><input type="radio" name="answer" checked={answer===option} onChange={()=>onAnswer(option)}/><span>{option}</span></label>)}</div>}<div className="lesson-player-actions"><button type="button" className="action-secondary" onClick={onSupport} disabled={stage==='level3'}>I need help</button><button type="button" className="action-primary" onClick={onPass} disabled={stage==='level2'?checks.length===0:!answer.trim()}>Submit answer</button></div></div>}